services:
  Minimalist-Web-Notepad:
    image: ghcr.io/gaoyaxuan/minimalist-web-notepad:latest
    container_name: minimalist-web-notepad
    restart: always
    network_mode: bridge
    environment:
    - "PERSISTENCE=false"
    - "PUID=1001"
    - "PGID=1001"
    - "TZ=Asia/Shanghai"
    ports:
      - "8080:3000"